/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javadestopbanhang;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javadestopbanhang.Users.Users;
import javadestopbanhang.connectDB.MyDB;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class NVban_hang extends javax.swing.JFrame {

    
    private Connection con ;
    private ResultSet rs;
    private PreparedStatement ps;
    
    private int thd = 0;
    int total = 0;
    boolean ckeckCHD = true ;
    
    /**
     * Creates new form NVban_hang
     */
    public NVban_hang(LoginForm lg ,Users u){
        super();
        namenv.setText(u.getName());
        initComponents();
        MyDB m = new MyDB();
        try {
            con = m.getConnect();
        } catch (SQLException ex) {
            
        }
    }
    public NVban_hang()  {
        initComponents();
        namenv.setText(Users.name);
        try {
            MyDB m = new MyDB();
            con = m.getConnect();
        } catch (Exception e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHD = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        namenv = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfEmailKh = new javax.swing.JTextField();
        tfTenKH = new javax.swing.JTextField();
        tfDCKH = new javax.swing.JTextField();
        tfSDTKH = new javax.swing.JTextField();
        btnCustomer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfMa = new javax.swing.JTextField();
        tfTenhang = new javax.swing.JTextField();
        tfSL = new javax.swing.JTextField();
        tfDonGia = new javax.swing.JTextField();
        tfThanhTien = new javax.swing.JTextField();
        jBtnHoaDoCT = new javax.swing.JButton();
        btnThanhtoan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbLH = new javax.swing.JComboBox<>();
        tfSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lbTotalBill = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHD);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bảng Hóa Đơn");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setText("Nhân Viên : ");

        namenv.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        namenv.setText("jLabel13");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin khách hàng"));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Tên ");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Email");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Địa Chỉ");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("SĐT");

        btnCustomer.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javadestopbanhang/image/customer.png"))); // NOI18N
        btnCustomer.setText("Customer");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(tfDCKH, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfEmailKh, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                .addComponent(tfTenKH))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(tfSDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel7, jLabel8, jLabel9});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfDCKH, tfSDTKH});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmailKh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDCKH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnCustomer))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfDCKH, tfEmailKh, tfSDTKH, tfTenKH});

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin mặt hàng"));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Mã Hàng");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Tên Hàng");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Số Lượng");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Đơn Giá");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Thành Tiền");

        tfMa.setEditable(false);

        tfTenhang.setEditable(false);

        tfDonGia.setEditable(false);

        tfThanhTien.setEditable(false);

        jBtnHoaDoCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javadestopbanhang/image/next-2-icon.png"))); // NOI18N
        jBtnHoaDoCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHoaDoCTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnHoaDoCT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(tfTenhang, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfDonGia, tfMa, tfSL, tfTenhang, tfThanhTien});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfMa, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfTenhang)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfSL)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfDonGia)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfThanhTien, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnHoaDoCT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfDonGia, tfMa, tfSL, tfTenhang});

        btnThanhtoan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnThanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javadestopbanhang/image/Pay-Per-Click-icon.png"))); // NOI18N
        btnThanhtoan.setText("Pay");
        btnThanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhtoanActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        cbLH.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbLH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Hàng", "Tên Hàng" }));

        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javadestopbanhang/image/search-icon (1).png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cbLH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addGap(26, 26, 26))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSearch)
                            .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbLH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );

        lbTotalBill.setText("Tổng tiền");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(btnThanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(namenv, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namenv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnThanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void showData(){
        String ma = tfSearch.getText();
        Vector col = new Vector ();
        
        col.addElement("Mã Hàng");
        col.addElement("Tên Hàng");
        col.addElement("Số Lượng");
        col.addElement("Đơn Giá");
        col.addElement("Loại Hàng");
        
        Vector data = new Vector();
        
        try {
            String sql ="SELECT * FROM mat_hang ";
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            while(rs.next()){
                Vector x = new Vector ();
                x.addElement("id");
                x.addElement("ten_hang");
                x.addElement("so_luong");
                x.addElement("don_gia");
                x.addElement("loai_hang");
               
                data.add(x);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
             tbHD.setModel(new DefaultTableModel(data, col));
    }
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        String textSearch = tfSearch.getText().toLowerCase().trim();
        String cbxrole = cbLH.getSelectedItem().toString();
        Vector col =new Vector();
        //Tạo tên cột
        col.addElement("Mã Hàng");
        col.addElement("Tên Hàng");
        col.addElement("Đơn Giá");
        col.addElement("Loại Hàng");
        //Tạo vecto dữ liệu
        Vector data = new Vector();

        switch(cbxrole)
        {
            case "Mã Hàng" :
            try {
                    String sqlql = "SELECT * FROM mat_hang WHERE idmh = ?";
                    ps=con.prepareStatement(sqlql);
                    ps.setString(1,textSearch);
                    rs=ps.executeQuery();
                    if (!rs.next()){
                    JOptionPane.showMessageDialog(this, "Không tồn tại mã hàng", "Error", JOptionPane.ERROR_MESSAGE);
                    }else{
                       
                   Vector u = new Vector();
                   u.addElement(rs.getString("idmh"));
                   u.addElement(rs.getString("ten_hang"));
                   u.addElement(rs.getString("don_gia"));
                   u.addElement(rs.getString("loai_hang"));
                   
                   data.add(u);

                    }
                         
                } catch (Exception e) {
                    e.printStackTrace();
                }
            break;
            case "Tên Hàng" :
            try {
                    String sqla = "SELECT * FROM mat_hang WHERE ten_hang LIKE ? ";
                   
                    ps=con.prepareStatement(sqla);
                    ps.setString(1,"%"+textSearch+"%");
                    rs=ps.executeQuery();
                    while(rs.next()){
                   Vector u = new Vector();
                   u.addElement(rs.getString("idmh"));
                   u.addElement(rs.getString("ten_hang"));
                   u.addElement(rs.getString("so_luong"));
                   u.addElement(rs.getString("don_gia"));
                   u.addElement(rs.getString("loai_hang"));
                   
                   data.add(u);

                }
 
                } catch (Exception e) {
                    e.printStackTrace();
                }
            break;
       
              
        }
        tbHD.setModel(new DefaultTableModel(data, col));
        System.out.println("hihi" + cbxrole);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhtoanActionPerformed
        
        
       
         try {
            String sql = "DELETE FROM gio_hang";
            ps=con.prepareStatement(sql);
            ps.executeUpdate();
        } catch (Exception e) {
        }
         JOptionPane.showMessageDialog(this, "Giao dịch thành công");
         btnCustomer.setEnabled(true);
         

         // thực hiện ghi file.
      
                        JFileChooser jfc = new JFileChooser();
        jfc.setCurrentDirectory(new File("D:\\user"));
        int temp = jfc.showSaveDialog(this);
        if(temp ==JFileChooser.APPROVE_OPTION){
            File f = jfc.getSelectedFile();
            try{
               
                    FileWriter out = new FileWriter(f+".doc");
                    BufferedWriter writer = new BufferedWriter(out);
                    DefaultTableModel model = (DefaultTableModel) tbHD.getModel();
                    
                    writer.write("Công ty trách nhiệm hữu hạn ABC\n");
                    writer.write("--------------Hóa Đơn---------------- \n\n\n\n");
                       writer.write("Khách hàng : "+tfTenKH.getText());
                       writer.write("\nEmail : "+tfEmailKh.getText());
                       writer.write("\nSDT : " + tfSDTKH.getText());
                       writer.write("\nĐịa chỉ : "+tfDCKH.getText()+"\n\n\n");
                    for (int j  = 0;j<model.getColumnCount();j++){
                        writer.write(model.getColumnName(j)+"\t");
                    }
                    writer.write("\n\n\n\n");
                    for(int j = 0;j<model.getRowCount();j++){
                        for (int k =0;k<model.getColumnCount();k++){
                            writer.write(model.getValueAt(j, k) + "\t\t");
                        }
                        writer.write("\n");
                    }
                    writer.write("Tổng tiền : "+thd);
                    writer.write("Nhân Viên : "+namenv.getText());
                    writer.close();
                    JOptionPane.showMessageDialog(this, "Lưu thành công");
            }catch(Exception e){
                    e.printStackTrace();
            }
       
       
              tfEmailKh.setText("");
         tfTenKH.setText("");
         tfSearch.setText("");
         tfDCKH.setText("");
         tfSDTKH.setText("");
      
        }
               
    }//GEN-LAST:event_btnThanhtoanActionPerformed

    private void tbHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHDMouseClicked
         int row = tbHD.getSelectedRow();
        if(row !=-1){
            tfMa.setText(tbHD.getValueAt(row, 0).toString());
            tfTenhang.setText(tbHD.getValueAt(row, 1).toString());
           
            tfDonGia.setText(tbHD.getValueAt(row, 2).toString());
           
        }
    }//GEN-LAST:event_tbHDMouseClicked

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
              try {
             
            if(tfTenKH.getText().length() == 0||tfEmailKh.getText().length() == 0||
                    tfSDTKH.getText().length() == 0||tfDCKH.getText().length() == 0){
                    JOptionPane.showMessageDialog(this, "Xin điền đầy đủ thông "
                            + "tin khách hàng");
                   
            }else{
                JOptionPane.showMessageDialog(this, "Nhập thông "
                            + "tin khách hàng thành công");
                String sql = "INSERT INTO khachhang(email,name,numberphone,address)"
               + "VALUES(?,?,?,?)";
                    ps=con.prepareStatement(sql);
                    ps.setString(2,tfTenKH.getText());
                    ps.setString(1,tfEmailKh.getText());
                    ps.setString(3,tfSDTKH.getText());
                    ps.setString(4,tfDCKH.getText());
                      ps.executeUpdate();
                      btnCustomer.setEnabled(false);
                      ckeckCHD = false;
                      
                      try {
                     String sqld = "INSERT INTO hoadon(idnvbh,email_kh)"
                       + "VALUES(?,?)";
                     ps=con.prepareStatement(sqld);
                     ps.setInt(1, Integer.parseInt(Users.id));
                     ps.setString(2,tfEmailKh.getText());
                     ps.executeUpdate();
                } catch (Exception e) {
                }
                      
                      

            }
  
            }catch(Exception e){
                
    }//GEN-LAST:event_btnCustomerActionPerformed
    }
    private void jBtnHoaDoCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHoaDoCTActionPerformed
        checkCreateHoaDon();

    }//GEN-LAST:event_jBtnHoaDoCTActionPerformed

    
    public void checkCreateHoaDon(){
       if (!ckeckCHD){
           // query hoa don chi tiet
           String sqlhd = "INSERT INTO hoadon_chitiet(idmh, soluong) "
                   + "VALUES(?,?)";
           try {
            ps = con.prepareStatement(sqlhd);
            ps.setString(1,tfMa.getText());
            ps.setString(2,tfSL.getText());
            ps.executeUpdate();
            
            String sqlin = "INSERT INTO hoadon_chitiethoadon(id_hoadon, id_hoadon_chitiet)"
                    + "VALUES ((SELECT MAX(idhoadon) FROM hoadon), "
                    + "(SELECT MAX(idhoadon_chitiet) FROM hoadon_chitiet) )";
            ps = con.prepareStatement(sqlin);
            ps.executeUpdate();
            
           } catch (Exception e) {
           }
           
           int sl =Integer.parseInt(tfSL.getText());
            int dg = Integer.parseInt(tfDonGia.getText());
            int total = 0;
            total = sl*dg;
            tfThanhTien.setText(String.valueOf(total));
            
           try{
               //check số lượng sản phẩm có trong kho.
               int slold = 0;
               String sqla = "SELECT * FROM mat_hang WHERE idmh = ? ";

                ps=con.prepareStatement(sqla);
                ps.setString(1,tfMa.getText());
                rs=ps.executeQuery();
                if (rs.next()){
                      slold = Integer.parseInt(rs.getString("so_luong"));
                      if (slold > sl){
                          try {
                                String sqlsub = "UPDATE mat_hang SET so_luong = ?"
                                  + " WHERE idmh = ?";
                                ps=con.prepareStatement(sqlsub);
                                ps.setString(1,String.valueOf(slold - sl));
                                ps.setInt(2,Integer.parseInt(tfMa.getText()));
                          
                               
                                ps.executeUpdate();
                          } catch (Exception e) {
                          }
                    
                      }

                }
                
               // support sofware ez
            String sql = "INSERT INTO  gio_hang(idgio_hang,ten_hang,so_luong,don_gia,thanh_tien)"
            + "VALUES(?,?,?,?,?)";
            ps=con.prepareStatement(sql);
            ps.setString(1,tfMa.getText());
            ps.setString(2,tfTenhang.getText());
            ps.setString(3,tfSL.getText());
            ps.setString(4,tfDonGia.getText());
            ps.setString(5,tfThanhTien.getText());

            ps.executeUpdate();

        }catch(Exception e){

        }
           //Total bill
           int t = 0; 
           int k = 0;
            try {
            String sql = "SELECT * FROM gio_hang";
           ps=con.prepareStatement(sql);
           rs=ps.executeQuery();
           while(rs.next()){
           t = Integer.parseInt(rs.getString("thanh_tien"));
           k+=t;
            
           }
         
        } catch (Exception e) {
        }
        lbTotalBill.setText("Tổng tiền : " +k);
        
           //show table
        Vector data = new Vector();
        Vector col = new Vector();

        col.addElement("Mã Hàng");
        col.addElement("Tên Hàng");
        col.addElement("Số Lượng");
        col.addElement("Đơn Giá");
        //col.addElement("Loại Hàng");
        col.addElement("Thành Tiền");
        try {
            String sqll = "SELECT * FROM  gio_hang";
            ps=con.prepareStatement(sqll);
            rs=ps.executeQuery();
            while(rs.next()){
                Vector temp = new Vector();

                temp.addElement(rs.getString("idgio_hang"));
                temp.addElement(rs.getString("ten_hang"));
                temp.addElement(rs.getString("so_luong"));
                temp.addElement(rs.getString("don_gia"));
                temp.addElement(rs.getString("thanh_tien"));

                data.add(temp);
            }
        } catch (Exception e) {
        }

        tbHD.setModel(new DefaultTableModel(data, col));
        
        //Cập nhật lại số lượng 
            
       }else{
           JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin khách hàng trước"
                   + " khi sử dụng dịch vụ !" ,"Error" , JOptionPane.ERROR_MESSAGE);
           btnCustomer.setEnabled(true);
       }
    }
    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NVban_hang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NVban_hang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NVban_hang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NVban_hang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NVban_hang q = new NVban_hang();
                 q.pack();
                 q.setLocationRelativeTo(null);
                 q.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnThanhtoan;
    private javax.swing.JComboBox<String> cbLH;
    private javax.swing.JButton jBtnHoaDoCT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTotalBill;
    private javax.swing.JLabel namenv;
    private javax.swing.JTable tbHD;
    private javax.swing.JTextField tfDCKH;
    private javax.swing.JTextField tfDonGia;
    private javax.swing.JTextField tfEmailKh;
    private javax.swing.JTextField tfMa;
    private javax.swing.JTextField tfSDTKH;
    private javax.swing.JTextField tfSL;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfTenKH;
    private javax.swing.JTextField tfTenhang;
    private javax.swing.JTextField tfThanhTien;
    // End of variables declaration//GEN-END:variables
}
