/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javadestopbanhang;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.*;
import java.util.Vector;
import javadestopbanhang.Users.Users;
import javadestopbanhang.connectDB.MyDB;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class QuanLiMH extends javax.swing.JFrame {

    private Connection con;
    private ResultSet rs;
    PreparedStatement ps;
    
    /**
     * Creates new form QuanLiMH
     */
    public QuanLiMH() {
        initComponents();
        namTK.setText(Users.name);
        try {
            MyDB mb = new MyDB();
            con=mb.getConnect();
        } catch (Exception e) {
        }
        showData();
    }
    

    public void showData(){
        Vector col = new Vector();
        
        col.addElement("Mã Hàng");  
        col.addElement("Tên Hàng");
        col.addElement("Số Lượng");
        col.addElement("Đơn Giá (£)");
        col.addElement("Loại Hàng");
        
        
       Vector data = new Vector();
       
        try {
            String sql = "SELECT * FROM mat_hang";
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
       while(rs.next()){
           Vector mh = new Vector();
                   
           mh.addElement(rs.getString("idmh"));
           mh.addElement(rs.getString("ten_hang"));
           mh.addElement(rs.getString("so_luong"));
           mh.addElement(rs.getString("don_gia"));
           mh.addElement(rs.getString("loai_hang"));
           
           data.add(mh);
          
       }
        } catch (Exception e) {
            e.printStackTrace();
        }
          tblMh.setModel(new DefaultTableModel(data,col));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tbMH = new javax.swing.JScrollPane();
        tblMh = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfIdMH = new javax.swing.JTextField();
        cbxLoaiHang = new javax.swing.JComboBox<>();
        tfTenHang = new javax.swing.JTextField();
        tfSoluong = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnAddMH = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        tfDongia = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cbxtypeSearch = new javax.swing.JComboBox<>();
        tfSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        namTK = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuXuatDS = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lí mặt hàng");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Manage items");

        tblMh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMhMouseClicked(evt);
            }
        });
        tbMH.setViewportView(tblMh);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Information"));

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Id");

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tên hàng");

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Số lượng");

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Đơn giá");

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Loại Hàng");

        tfIdMH.setEnabled(false);

        cbxLoaiHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Điện Thoại", "Máy Tính ", "Các  Loại Khác" }));

        btnAddMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javadestopbanhang/image/mh_add.png"))); // NOI18N
        btnAddMH.setText("Thêm mới");
        btnAddMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMHActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javadestopbanhang/image/Apps-system-software-update-icon.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javadestopbanhang/image/Document-Delete-icon.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAddMH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddMH)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxLoaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfIdMH, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSoluong, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(tfTenHang))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfDongia, tfIdMH, tfSoluong, tfTenHang});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfIdMH, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTenHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfDongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cbxLoaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfDongia, tfIdMH, tfSoluong, tfTenHang});

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        cbxtypeSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbxtypeSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Mã Hàng", "Tên Hàng" }));

        btnSearch.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javadestopbanhang/image/search-icon (1).png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(cbxtypeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSearch)
                .addGap(44, 44, 44))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxtypeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setText("Thủ Kho :");

        namTK.setText("jLabel8");

        jMenu1.setText("File");

        mnuXuatDS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javadestopbanhang/image/Save-icon.png"))); // NOI18N
        mnuXuatDS.setText("Xuát danh sách");
        mnuXuatDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuXuatDSActionPerformed(evt);
            }
        });
        jMenu1.add(mnuXuatDS);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbMH)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namTK, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namTK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(tbMH, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(324, 324, 324)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(332, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMHActionPerformed
      
        String sqlkt = "SELECT * FROM mat_hang WHERE ten_hang = ?";
        try {
                ps=con.prepareStatement(sqlkt);
                ps.setString(1, tfTenHang.getText());
                rs=ps.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Sản phẩm bị trùng tên hàng");
                }else{
    
                String sql ="INSERT INTO mat_hang(ten_hang,so_luong,don_gia,loai_hang)"
                + "VALUES (?,?,?,?)"  ;
          
                ps=con.prepareStatement(sql);

                
                ps.setString(1, tfTenHang.getText());
                ps.setString(2, tfSoluong.getText());
                ps.setString(3, tfDongia.getText());
                ps.setString(4, cbxLoaiHang.getSelectedItem().toString());

                ps.executeUpdate();

        }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
        showData();
    
    }//GEN-LAST:event_btnAddMHActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       String sql = "UPDATE mat_hang SET ten_hang = ?,so_luong = ?,"
               + "don_gia = ?,loai_hang = ? WHERE idmh = ?";
       
        try {
            ps=con.prepareStatement(sql);
            ps.setString(1, tfTenHang.getText());
            ps.setString(2,tfSoluong.getText());
            ps.setString(3,tfDongia.getText());
            ps.setString(4,cbxLoaiHang.getSelectedItem().toString());
            ps.setString(5,tfIdMH.getText());
            
            ps.executeUpdate();

        } catch (Exception e) {
            e.printStackTrace();
        }
        showData();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblMhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMhMouseClicked
        int row = tblMh.getSelectedRow();
        if(row !=-1){
            String id = (String) tblMh.getValueAt(row,0 );
            tfIdMH.setText(id);
            tfTenHang.setText(tblMh.getValueAt(row, 1).toString());
            tfSoluong.setText(tblMh.getValueAt(row, 2).toString());
            tfDongia.setText(tblMh.getValueAt(row, 3).toString());
            cbxLoaiHang.setSelectedItem(tblMh.getValueAt(row, 4).toString());
        }
    }//GEN-LAST:event_tblMhMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
      
        try {
              String sql = "DELETE FROM mat_hang WHERE idmh = ? ";
              ps=con.prepareStatement(sql);
              ps.setString(1, tfIdMH.getText());
              ps.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
        showData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void mnuXuatDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuXuatDSActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setCurrentDirectory(new File("D:\\user"));
        int temp = jfc.showSaveDialog(this);
        if(temp ==JFileChooser.APPROVE_OPTION){
            File f = jfc.getSelectedFile();
            try{
               
                    FileWriter out = new FileWriter(f+".doc");
                    BufferedWriter writer = new BufferedWriter(out);
                    DefaultTableModel model = (DefaultTableModel) tblMh.getModel();
                    
                    writer.write("Công ty trách nhiệm hữu hạn Trần Thế Lâm\n\n");
                    writer.write("\n----------DANH SÁCH HÀNG TRONG KHO------------\n\n\n\n");
                    for (int j  = 0;j<model.getColumnCount();j++){
                        writer.write(model.getColumnName(j)+"\t");
                    }
                    writer.write("\n\n");
                    for(int j = 0;j<model.getRowCount();j++){
                        for (int k =0;k<model.getColumnCount();k++){
                            writer.write(model.getValueAt(j, k) + "\t\t\t");
                        }
                        writer.write("\n\n");
                    }
                    writer.write("Thủ kho : "+namTK.getText());
                    writer.close();
                    JOptionPane.showMessageDialog(this, "Lưu thành công");
            }catch(Exception e){
                    e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_mnuXuatDSActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
         String textSearch = tfSearch.getText().toLowerCase().trim();
         String cbxrole = cbxtypeSearch.getSelectedItem().toString();
           Vector col =new Vector();
        //Tạo tên cột 
        col.addElement("Mã Hàng");
        col.addElement("Tên Hàng");
        col.addElement("Số Lượng");
        col.addElement("Đơn Giá");
        col.addElement("Loại Hàng");
        //Tạo vecto dữ liệu
        Vector data = new Vector();
        
        switch(cbxrole)
        {
            case "All" :
                
                try {
                    String sql = "SELECT * FROM mat_hang";
                    ps=con.prepareStatement(sql);
                    rs=ps.executeQuery();
                while(rs.next()){
                   Vector u = new Vector();
                   u.addElement(rs.getString("idmh"));
                   u.addElement(rs.getString("ten_hang"));
                   u.addElement(rs.getString("so_luong"));
                   u.addElement(rs.getString("don_gia"));
                   u.addElement(rs.getString("loai_hang"));
                    if(u.toString().toLowerCase().contains(textSearch)){
                data.add(u);
            } 
               
                }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
                break;
            case "Mã Hàng" :
                try {
                    String sqlql = "SELECT * FROM mat_hang WHERE idmh = ?";
                    ps=con.prepareStatement(sqlql);
                    ps.setString(1,textSearch);
                    rs=ps.executeQuery();
                while(rs.next()){
                   Vector u = new Vector();
                   u.addElement(rs.getString("idmh"));
                   u.addElement(rs.getString("ten_hang"));
                   u.addElement(rs.getString("so_luong"));
                   u.addElement(rs.getString("don_gia"));
                   u.addElement(rs.getString("loai_hang"));
                   
                   data.add(u);

                }
                         
                } catch (Exception e) {
                    e.printStackTrace();
                }
                break;
            case "Tên Hàng" :
                try {
                    String sqla = "SELECT * FROM mat_hang WHERE ten_hang LIKE ? ";
                   
                    ps=con.prepareStatement(sqla);
                    ps.setString(1,"%"+textSearch+"%");
                    rs=ps.executeQuery();
                while(rs.next()){
                   Vector u = new Vector();
                   u.addElement(rs.getString("idmh"));
                   u.addElement(rs.getString("ten_hang"));
                   u.addElement(rs.getString("so_luong"));
                   u.addElement(rs.getString("don_gia"));
                   u.addElement(rs.getString("loai_hang"));
                   
                   data.add(u);

                }
    
                } catch (Exception e) {
                    e.printStackTrace();
                }
                break;
                
             }
              tblMh.setModel(new DefaultTableModel(data, col));
              System.out.println("Lamtt"+ cbxrole);
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiMH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiMH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiMH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiMH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               QuanLiMH q = new QuanLiMH();
                 q.pack();
                 q.setLocationRelativeTo(null);
                 q.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMH;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxLoaiHang;
    private javax.swing.JComboBox<String> cbxtypeSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem mnuXuatDS;
    private javax.swing.JLabel namTK;
    private javax.swing.JScrollPane tbMH;
    private javax.swing.JTable tblMh;
    private javax.swing.JTextField tfDongia;
    private javax.swing.JTextField tfIdMH;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfSoluong;
    private javax.swing.JTextField tfTenHang;
    // End of variables declaration//GEN-END:variables
}
