
import db.KhachHangDB;
import db.LichDB;
import db.LichSpaDB;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;
import model.Lich;
import model.LichSpa;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lamtran
 */
public class HienThiLichTrongFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form HienThiLichTrong
     */
    static int maLSpa = 0;
    static String sdt_khachhang = "";
    static KhachHangDB khdb = new KhachHangDB();
    public HienThiLichTrongFrame() {
        initComponents();
        LichSpaDB lsd = new LichSpaDB();
        showData(lsd.get_lich_trong("2019-12-19 08:20:00"));
        btThemmoi.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfSdt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfTen = new javax.swing.JTextField();
        tfDiachi = new javax.swing.JTextField();
        btnTimSdt = new javax.swing.JButton();
        btThemmoi = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbShowLichTrong = new javax.swing.JTable();
        btHoanTat = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhap thong tin khach hang"));
        jPanel3.setName(""); // NOI18N

        jLabel2.setText("ten");

        tfSdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSdtActionPerformed(evt);
            }
        });

        jLabel3.setText("sodt");

        jLabel4.setText("email");

        jLabel5.setText("diachi");

        btnTimSdt.setText("Kiemtra");
        btnTimSdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimSdtActionPerformed(evt);
            }
        });

        btThemmoi.setText("Them moi");
        btThemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemmoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnTimSdt)
                        .addGap(31, 31, 31)
                        .addComponent(btThemmoi))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfTen, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(32, 32, 32)
                            .addComponent(tfDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfDiachi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimSdt)
                    .addComponent(btThemmoi))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tim Lich Trong"));

        tbShowLichTrong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbShowLichTrong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbShowLichTrongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbShowLichTrong);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        btHoanTat.setText("HoanTat");
        btHoanTat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoanTatActionPerformed(evt);
            }
        });

        btCancel.setText("HuyBo");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCancel)
                        .addGap(71, 71, 71)
                        .addComponent(btHoanTat)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHoanTat)
                    .addComponent(btCancel))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSdtActionPerformed

    private void btnTimSdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimSdtActionPerformed
        // TODO add your handling code here:
        
        if (tfSdt.getText().trim().length() != 0) {
            KhachHang kh  = khdb.get_by_sodt(tfSdt.getText().trim());
            if (kh != null) {
                JOptionPane.showMessageDialog(HienThiLichTrongFrame.this, "Khach hang : " + kh.getTen()  ,
                        "Thong tin khach hang" , JOptionPane.INFORMATION_MESSAGE);
                btThemmoi.setEnabled(false);
            }else {
                JOptionPane.showMessageDialog(HienThiLichTrongFrame.this, "Khach hang moi" ,
                        "Yeu cau them moi" , JOptionPane.WARNING_MESSAGE);
                btThemmoi.setEnabled(true);
            }
           
        }
    }//GEN-LAST:event_btnTimSdtActionPerformed

    private void btThemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemmoiActionPerformed
        try {
            // TODO add your handling code here:
            //insert kh vao db
            String ten = tfTen.getText();
            String email = tfEmail.getText();
            String sdt = tfSdt.getText();
            String diachi = tfDiachi.getText();
            if (ten.length() == 0 || sdt.length() == 0) {
                JOptionPane.showMessageDialog(HienThiLichTrongFrame.this, "Nhap day du thong tin cho ten va so dien thoai"  ,
                        "Loi" , JOptionPane.ERROR_MESSAGE);
                return;
            }
            KhachHang kh = new KhachHang( ten, sdt, email, diachi);
            khdb.insert(kh);
            JOptionPane.showMessageDialog(HienThiLichTrongFrame.this, "Them moi thanh cong"  ,
                        "Thanh cong" , JOptionPane.PLAIN_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(HienThiLichTrongFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btThemmoiActionPerformed

    private void btHoanTatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoanTatActionPerformed
        // TODO add your handling code here:
        
        if (maLSpa != 0 && khdb.get_by_sodt(tfSdt.getText()) != null) {
            try {
                Lich l = new Lich(maLSpa, tfSdt.getText(), 0, NhanhKhachFrame.nv.getMaNV());
                LichDB ldb = new LichDB(l);
                NhanhKhachFrame.maL = ldb.insert();
                LichSpaDB lsdb = new LichSpaDB();
                lsdb.update(maLSpa, 1);
                HienThiLichTrongFrame.this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(HienThiLichTrongFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(HienThiLichTrongFrame.this, "Kiem tra lai lich va thong tin khach hang"  ,
                        "Loi" , JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btHoanTatActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        HienThiLichTrongFrame.this.setVisible(false);
    }//GEN-LAST:event_btCancelActionPerformed

    private void tbShowLichTrongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShowLichTrongMouseClicked
        // TODO add your handling code here:
        int row = tbShowLichTrong.getSelectedRow();
        if (row != -1) {
            maLSpa = (int) tbShowLichTrong.getValueAt(row, 0);
            System.out.println(maLSpa);
        }
    }//GEN-LAST:event_tbShowLichTrongMouseClicked

    public void showData(List<LichSpa> list){
        Vector col = new Vector();
        col.addElement("Ma Lich");
        col.addElement("Thoi gian"); 
        
        
       Vector data = new Vector();
       for (int i = 0; i< list.size(); i++) {
           Vector mh = new Vector();
           mh.addElement(list.get(i).getMalsp());
           mh.addElement(list.get(i).getThoigian());
           data.add(mh);
       }
      
        tbShowLichTrong.setModel(new DefaultTableModel(data,col));
         
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HienThiLichTrongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HienThiLichTrongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HienThiLichTrongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HienThiLichTrongFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HienThiLichTrongFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btHoanTat;
    private javax.swing.JButton btThemmoi;
    private javax.swing.JButton btnTimSdt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbShowLichTrong;
    private javax.swing.JTextField tfDiachi;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfSdt;
    private javax.swing.JTextField tfTen;
    // End of variables declaration//GEN-END:variables
}
