
import db.DichVuDB;
import db.HoaDonDB;
import db.HoaDonDVNLDB;
import db.KhachHangDB;
import db.LichDB;
import db.NguyenLieuDB;
import db.NhanVienDB;
import db.NhanVienDichVuDB;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DichVu;
import model.HoaDon;
import model.HoaDonDVNL;

import model.KhachHang;
import model.Lich;
import model.NguyenLieu;
import model.NhanVien;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author beetsoft
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    //truyenf thoong tin cua nhan vien vao day 
    
    static boolean is_show = false;
    static NhanVien nv = null;
    static int maHD = 0; 
    static int maL = 0;
    public MainFrame() {
        initComponents();
        clearData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel_search_lich = new javax.swing.JPanel();
        tfSearchNameKH = new javax.swing.JTextField();
        btnSearchKhach = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbShowLich = new javax.swing.JTable();
        btnTaoLich = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pannel_add_dv_nl = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tbl_choose_nv = new javax.swing.JScrollPane();
        tbShowNVPV = new javax.swing.JTable();
        btChonLaiNVPV = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        panel_search_dv_nl = new javax.swing.JPanel();
        tfSearchNLDV = new javax.swing.JTextField();
        btnSearchDVNL = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbShowDVNL = new javax.swing.JTable();
        btHoanTatDVNL = new javax.swing.JButton();
        btBackDVNL = new javax.swing.JButton();
        cbDVNL = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbShowBillTamTinh = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lbTongtienTamTinh = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbTenKH = new javax.swing.JLabel();
        lbSdtKH = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbLich = new javax.swing.JLabel();
        btHoanTatNhanKhach = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel1.setText("Chuc nang nhan khach");

        panel_search_lich.setBackground(new java.awt.Color(242, 242, 240));
        panel_search_lich.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tim lich dat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        tfSearchNameKH.setToolTipText("Nhap ten");
        tfSearchNameKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchNameKHActionPerformed(evt);
            }
        });

        btnSearchKhach.setText("Tim");
        btnSearchKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchKhachActionPerformed(evt);
            }
        });

        tbShowLich.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Tran The Lam", "02323230203am", "lamtt@gmail.com", "09:30 2019-11-01"},
                {"Nguyen Văn Lam", "9423498a", "banv@gmail.com", "20:30 2019-11-01"}
            },
            new String [] {
                "Ten ", "So dien thoai", "Email", "Lich"
            }
        ));
        tbShowLich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbShowLichMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbShowLich);

        btnTaoLich.setText("Tao Lich");
        btnTaoLich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoLichActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_search_lichLayout = new javax.swing.GroupLayout(panel_search_lich);
        panel_search_lich.setLayout(panel_search_lichLayout);
        panel_search_lichLayout.setHorizontalGroup(
            panel_search_lichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_search_lichLayout.createSequentialGroup()
                .addGroup(panel_search_lichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_search_lichLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panel_search_lichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(panel_search_lichLayout.createSequentialGroup()
                                .addComponent(tfSearchNameKH, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(btnSearchKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_search_lichLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTaoLich, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_search_lichLayout.setVerticalGroup(
            panel_search_lichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_search_lichLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_search_lichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearchNameKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchKhach))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTaoLich)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pannel_add_dv_nlLayout = new javax.swing.GroupLayout(pannel_add_dv_nl);
        pannel_add_dv_nl.setLayout(pannel_add_dv_nlLayout);
        pannel_add_dv_nlLayout.setHorizontalGroup(
            pannel_add_dv_nlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1293, Short.MAX_VALUE)
        );
        pannel_add_dv_nlLayout.setVerticalGroup(
            pannel_add_dv_nlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chon nhan vien phuc vu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        tbShowNVPV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Cat toc", "1", "Tran Van A"},
                {"3", "Goi Dau", "2", "Nguyen Van B"}
            },
            new String [] {
                "MaDV", "TenDV", "MaNV", "TenNV"
            }
        ));
        tbShowNVPV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbShowNVPVMouseClicked(evt);
            }
        });
        tbl_choose_nv.setViewportView(tbShowNVPV);

        btChonLaiNVPV.setText("Chon lai NVPV");
        btChonLaiNVPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChonLaiNVPVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbl_choose_nv, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btChonLaiNVPV, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl_choose_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btChonLaiNVPV)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        panel_search_dv_nl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Them dich vu, nguyen lieu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        tfSearchNLDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchNLDVActionPerformed(evt);
            }
        });

        btnSearchDVNL.setText("Tim kiem");
        btnSearchDVNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDVNLActionPerformed(evt);
            }
        });

        tbShowDVNL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Cat toc nam", "50", "cat toc nam"},
                {"2", "Cat toc nu", "60", "cat toc nua"}
            },
            new String [] {
                "Ma", "Ten DV/NL", "Don gia(nghin vnd)", "Mo ta"
            }
        ));
        tbShowDVNL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbShowDVNLMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbShowDVNL);

        btHoanTatDVNL.setText("Hoan Tat");
        btHoanTatDVNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoanTatDVNLActionPerformed(evt);
            }
        });

        btBackDVNL.setText("Quay Lai");
        btBackDVNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackDVNLActionPerformed(evt);
            }
        });

        cbDVNL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dich vu", "Nguyen lie" }));

        javax.swing.GroupLayout panel_search_dv_nlLayout = new javax.swing.GroupLayout(panel_search_dv_nl);
        panel_search_dv_nl.setLayout(panel_search_dv_nlLayout);
        panel_search_dv_nlLayout.setHorizontalGroup(
            panel_search_dv_nlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_search_dv_nlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_search_dv_nlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(panel_search_dv_nlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cbDVNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfSearchNLDV, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchDVNL, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_search_dv_nlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBackDVNL)
                .addGap(62, 62, 62)
                .addComponent(btHoanTatDVNL)
                .addGap(54, 54, 54))
        );
        panel_search_dv_nlLayout.setVerticalGroup(
            panel_search_dv_nlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_search_dv_nlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_search_dv_nlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchDVNL)
                    .addComponent(tfSearchNLDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDVNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panel_search_dv_nlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHoanTatDVNL)
                    .addComponent(btBackDVNL))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hoa don tam tinh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        tbShowBillTamTinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Cat toc nam", "50", "1"},
                {"3", "Goi dau", "30", "1"}
            },
            new String [] {
                "Ma", "Ten DV/NL", "Don gia(nghin vnd)", "So luong"
            }
        ));
        tbShowBillTamTinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbShowBillTamTinhMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbShowBillTamTinh);

        jLabel2.setText("Tong tien :");

        lbTongtienTamTinh.setText("80");

        jLabel4.setText("(nghin vnd)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addComponent(lbTongtienTamTinh)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbTongtienTamTinh)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Ten khach hang:");

        jLabel5.setText("So dien thoai:");

        jLabel6.setText("Email:");

        jLabel7.setText("Lich:");

        lbTenKH.setText("jLabel8");

        lbSdtKH.setText("jLabel8");

        lbEmail.setText("jLabel8");

        lbLich.setText("jLabel8");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_search_dv_nl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSdtKH)
                            .addComponent(lbTenKH)
                            .addComponent(lbEmail)
                            .addComponent(lbLich))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(panel_search_dv_nl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbTenKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbSdtKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbLich))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btHoanTatNhanKhach.setText("Hoan tat");
        btHoanTatNhanKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoanTatNhanKhachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(513, 513, 513)
                        .addComponent(btHoanTatNhanKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pannel_add_dv_nl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel_search_lich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(474, 474, 474)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panel_search_lich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(pannel_add_dv_nl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btHoanTatNhanKhach)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHoanTatNhanKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoanTatNhanKhachActionPerformed
        try {
            // TODO add your handling code here:
            if (is_show){
                jLabel1.setEnabled(true);
                is_show = false;
                return;
            }
            jLabel1.setEnabled(false);
            is_show = true;
            
            if (tbShowNVPV.getRowCount() != 0) {
                JOptionPane.showMessageDialog(MainFrame.this, "Ban phai chon nhan vien phuc vu truoc khi hoan tat!" , "Canh bao" , JOptionPane.ERROR_MESSAGE);
                return;
            }
            //update lai status lich, update soluong nguyen lieu, update status nhan vien
            LichDB l = new LichDB();
            l.update(maL, 1);
            
            NhanVienDB nvdb = new NhanVienDB();
            HoaDonDVNLDB hoaDonDVNLDB = new HoaDonDVNLDB();
            NguyenLieuDB nguyenLieuDB = new NguyenLieuDB();
            NhanVienDB nhanVienDB = new NhanVienDB();
            for (HoaDonDVNL h : hoaDonDVNLDB.get_by_id_hd(maHD)) {
                
                if (h.getType() == 1) {
                    //cap nhat so luong
                    NguyenLieu nl = nguyenLieuDB.get_by_id(h.getMaDVNL());
                    int conlai = nl.getSoluong() - h.getSoluong();
                    nguyenLieuDB.updateSoluong(h.getMaDVNL(), conlai);
                } else {
                    // update status nhan vien
                    nhanVienDB.update(h.getMaNVPV(), 1);
                }
                
                
            clearData();
            
            JOptionPane.showMessageDialog(MainFrame.this, "Nhan khach thanh cong!" , "Thanh cong" , JOptionPane.INFORMATION_MESSAGE);
    
                
            } 
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btHoanTatNhanKhachActionPerformed

    private void clearData() {
        DefaultTableModel model = new DefaultTableModel();
        tbShowLich.setModel(model);
        tbShowBillTamTinh.setModel(model);
        tbShowNVPV.setModel(model);
        tbShowDVNL.setModel(model);
        
        lbEmail.setText("");
        lbLich.setText("");
        lbSdtKH.setText("");
        lbTenKH.setText("");
        lbTongtienTamTinh.setText("");
        lichEnable(true);
        
    }
    private void tfSearchNameKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchNameKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchNameKHActionPerformed

    private void btnSearchKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchKhachActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(this, "Hay dat lich cho khach khang",
//                "Khach hang chua dat lich", JOptionPane.YES_NO_OPTION);
        String ten = tfSearchNameKH.getText();
        KhachHangDB kdb = new KhachHangDB();
        LichDB ldb = new LichDB();
         List<KhachHang> lkh = null;
        
        //viet them cai select query list input listsdt kh output: list Lich
        if (ten.length() == 0) {
            lkh = kdb.get_all();
        } else {
            lkh = kdb.get_by_name(ten);
        }
        List<Lich> ll =  ldb.get_by_lstsdt_and_date(lkh, "2019-03-24");
        
        showData(ll);
        
    }//GEN-LAST:event_btnSearchKhachActionPerformed

    public void showData(List<Lich> list){
        Vector col = new Vector();
        col.addElement("Ma Lich");
        col.addElement("Ten");  
        col.addElement("So dien thoai");
        col.addElement("Email");
        col.addElement("Lich");
        
       Vector data = new Vector();
       for (int i = 0; i< list.size(); i++) {
           Vector mh = new Vector();
           String sdt = list.get(i).getSdtkhachhang();
           KhachHangDB kdb = new KhachHangDB();
           KhachHang kh = kdb.get_by_sodt(sdt);
           mh.addElement(list.get(i).getMaL());
           mh.addElement(kh.getTen());
           mh.addElement(kh.getSodt());
           mh.addElement(kh.getEmail());
           mh.addElement(list.get(i).getNgay());
           
           data.add(mh);
       }
      
        tbShowLich.setModel(new DefaultTableModel(data,col));
         
    }
    
    public void showDVNL(List<DichVu> l_dv, List<NguyenLieu> l_nl){
        Vector col = new Vector();
        
        col.addElement("Ma");  
        col.addElement("Ten");
        col.addElement("Don gia");
        col.addElement("Mota");
        col.addElement("So luong");
        
        Vector data = new Vector();
        
        if (l_dv != null) {
            for (int i = 0; i< l_dv.size(); i++) {
                Vector mh = new Vector();
                mh.addElement(l_dv.get(i).getMaDV());
                mh.addElement(l_dv.get(i).getTen());
                mh.addElement(l_dv.get(i).getDongia());
                mh.addElement(l_dv.get(i).getMota());
                mh.addElement(" ");
                data.add(mh);
            }
        }else {
            for (int i = 0; i< l_nl.size(); i++) {
                Vector mh = new Vector();
                mh.addElement(l_nl.get(i).getMaNL());
                mh.addElement(l_nl.get(i).getTen());
                mh.addElement(l_nl.get(i).getDongia());
                mh.addElement(l_nl.get(i).getMota());
                mh.addElement(l_nl.get(i).getSoluong());
                data.add(mh);
            }
        }
        tbShowDVNL.setModel(new DefaultTableModel(data,col));
    }
   
    public void showNVPV(boolean showallHddv){
        Vector col = new Vector();
        col.addElement("Ma DV");
        col.addElement("Dich Vu");  
        col.addElement("Nhan Vien");
        col.addElement("Ma nhanvien");
        col.addElement("Ma HDDVNL");
        Vector data = new Vector();
        
        HoaDonDVNLDB hddvnldb = new HoaDonDVNLDB();
        for (HoaDonDVNL h: hddvnldb.get_dv_by_id_hd(maHD, showallHddv)) {
            NhanVienDichVuDB nvdb = new NhanVienDichVuDB();
            DichVu dv = new DichVuDB().get_by_id(h.getMaDVNL());
           
            for (NhanVien nv : nvdb.get_by_dichvu_status(h.getMaDVNL())) {
                Vector mh = new Vector();
                mh.addElement(dv.getMaDV());
                mh.addElement(dv.getTen());
                mh.addElement(nv.getTen());
                mh.addElement(nv.getMaNV());
                mh.addElement(h.getMaHDDVNL());
                data.add(mh);
            }
        }
        
        tbShowNVPV.setModel(new DefaultTableModel(data,col));
        
        
    }
    
    public void showHoaDonTamTinh(){
        int total = 0;
        Vector col = new Vector();
        
        col.addElement("Ma");  
        col.addElement("Ten");
        col.addElement("Loai");
        col.addElement("Don gia");
        col.addElement("So luong");
        col.addElement("NhanVienPV");
        
        Vector data = new Vector();
        
        HoaDonDVNLDB h = new HoaDonDVNLDB();
        
        for (HoaDonDVNL hd : h.get_by_id_hd(maHD)) {
                Vector mh = new Vector();
                mh.addElement(hd.getMaDVNL());
                if (hd.getType() == 0) {
                    DichVuDB dvdb = new DichVuDB();
                    DichVu dv = dvdb.get_by_id(hd.getMaDVNL());
                    mh.addElement(dv.getTen());
                    mh.addElement("Dich vu");
                }else{
                    NguyenLieuDB nldb = new NguyenLieuDB();
                    NguyenLieu nl = nldb.get_by_id(hd.getMaDVNL());
                    mh.addElement(nl.getTen());
                    mh.addElement("Nguyen lieu");
                }
                mh.addElement(hd.getDongiahientai());
                mh.addElement(hd.getSoluong());
                
                if (hd.getMaNVPV() != 0) {
                    NhanVienDB nvdb = new NhanVienDB();
                    mh.addElement(nvdb.get_by_id(hd.getMaNVPV()).getTen());
                }else {
                    mh.addElement(" ");
                }
                total += hd.getDongiahientai() * hd.getSoluong();
                data.add(mh);
            }
        
        lbTongtienTamTinh.setText(total + "");
        tbShowBillTamTinh.setModel(new DefaultTableModel(data,col));
    }
    
    private void tfSearchNLDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchNLDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchNLDVActionPerformed

    private void btnSearchDVNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDVNLActionPerformed
        // TODO add your handling code here:
         int index = cbDVNL.getSelectedIndex();
         if (index == 0) {
             DichVuDB dvdb = new DichVuDB();
             List<DichVu> list = null;
             if (tfSearchNLDV.getText().length() == 0) {
                list = dvdb.get_all();
             } else {
                list = dvdb.get_by_name(tfSearchNLDV.getText());
             }
             showDVNL(list, null);
         } else {
             NguyenLieuDB nldb = new NguyenLieuDB();
             List<NguyenLieu> list = null;
             if (tfSearchNLDV.getText().length() == 0) {
                 list = nldb.get_all();
             } else {
                 list = nldb.get_by_name(tfSearchNLDV.getText());
             }
             showDVNL(null, list);
         }
         
         
    }//GEN-LAST:event_btnSearchDVNLActionPerformed

    private void btnTaoLichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoLichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaoLichActionPerformed

    private void btChonLaiNVPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChonLaiNVPVActionPerformed
        // TODO add your handling code here:
        showNVPV(true);
    }//GEN-LAST:event_btChonLaiNVPVActionPerformed

    private void tbShowLichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShowLichMouseClicked
        // TODO add your handling code here:
        int row = tbShowLich.getSelectedRow();
        if(row !=-1){
            try {
                int id = (int) tbShowLich.getValueAt(row,0 );
                lbTenKH.setText(tbShowLich.getValueAt(row,1 ).toString());
                lbSdtKH.setText(tbShowLich.getValueAt(row, 2).toString());
                lbEmail.setText(tbShowLich.getValueAt(row, 3).toString());
                lbLich.setText(tbShowLich.getValueAt(row, 4).toString());
                lichEnable(false);
                dichvuNLEnable(true);
                
                //write function create bill
                maL = id;
                HoaDon hd = new HoaDon(nv.getMaNV(), id, 0);
                HoaDonDB hdb = new HoaDonDB(hd);
                maHD = hdb.insert();
            } catch (SQLException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_tbShowLichMouseClicked
    
    
    
    private void btBackDVNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackDVNLActionPerformed
        try {
            // TODO add your handling code here:
            lichEnable(true);
            //write function detele all bill
            HoaDonDB hdb = new HoaDonDB();
            hdb.delete(maHD);
            HoaDonDVNLDB hdndb = new HoaDonDVNLDB();
            hdndb.delete_by_id(maHD);
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btBackDVNLActionPerformed

    
    private void btHoanTatDVNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoanTatDVNLActionPerformed
        // TODO add your handling code here:
        dichvuNLEnable(false);
        nhanvienPVEnable(true);
        showNVPV(false);
    }//GEN-LAST:event_btHoanTatDVNLActionPerformed

    private void tbShowDVNLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShowDVNLMouseClicked
        // TODO add your handling code here:
        int row = tbShowDVNL.getSelectedRow();
        if (row !=-1){
            
            String title = "Nhap so luong cho " + tbShowDVNL.getValueAt(row,1).toString() + " :";
            String soluong = JOptionPane.showInputDialog(MainFrame.this, title);
            if (soluong != null) {
                
                if (isNumeric(soluong) != -1) {
                    if (cbDVNL.getSelectedIndex() == 1) {
                        int value = (int) tbShowDVNL.getValueAt(row, 4);
                        if (isNumeric(soluong) > value) {
                            JOptionPane.showMessageDialog(MainFrame.this, "So luong ban nhap vuot qua " + value+ " so luong trong kho!" , "That bai" , JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                    }
                    try {
                        int maDV = (int) tbShowDVNL.getValueAt(row,0 );
                        int dongiahientai = (int) tbShowDVNL.getValueAt(row, 2);
                        HoaDonDVNL hddv = new HoaDonDVNL(maHD, maDV, 0, isNumeric(soluong), dongiahientai, cbDVNL.getSelectedIndex());
                        HoaDonDVNLDB hddvdb = new HoaDonDVNLDB(hddv);
                        hddvdb.insert();
                        showHoaDonTamTinh();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                
                } else {
                    JOptionPane.showMessageDialog(MainFrame.this, "Ki tu ban nhap phai la so! Vui long thuc hien lai", "That bai" , JOptionPane.WARNING_MESSAGE);
                }         
                        
                   
                } 
            } 
          
    }//GEN-LAST:event_tbShowDVNLMouseClicked

    private void tbShowBillTamTinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShowBillTamTinhMouseClicked
        // TODO add your handling code here:
        // Cap nhat lai so luong dich vu, nl , xoa (nhap 0)
    }//GEN-LAST:event_tbShowBillTamTinhMouseClicked

    private void tbShowNVPVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShowNVPVMouseClicked
        // TODO add your handling code here:
        int row = tbShowNVPV.getSelectedRow();
        if (row !=-1){
           //update hoa don dich vu nguyen lieu
           HoaDonDVNLDB hoaDonDVNLDB = new HoaDonDVNLDB();
           int maNV = (int) tbShowNVPV.getValueAt(row, 3);
           int maHDDVNL = (int) tbShowNVPV.getValueAt(row, 4);
           System.out.println(maNV + "___" + maHDDVNL);
           hoaDonDVNLDB.update_idNV(maNV, maHDDVNL);
           showNVPV(false);
           showHoaDonTamTinh();
        }
    }//GEN-LAST:event_tbShowNVPVMouseClicked
    
    public static int isNumeric(String strNum) {
        if (strNum == null) {
            return -1;
        }
        try {
            int d = Integer.parseInt(strNum);
            return d;
        } catch (NumberFormatException nfe) {
            return -1;
        }
    }
    
    private void lichEnable(boolean is_show) {
        tbShowLich.setEnabled(is_show);
        tfSearchNameKH.setEnabled(is_show);
        btnSearchKhach.setEnabled(is_show);
        btnTaoLich.setEnabled(is_show);
        
        if (is_show) {
            dichvuNLEnable(!is_show);
            nhanvienPVEnable(!is_show);
        }
        
    }
    
    
    private void dichvuNLEnable(boolean is_show) {
        tbShowDVNL.setEnabled(is_show);
        tfSearchNLDV.setEnabled(is_show);
        btnSearchDVNL.setEnabled(is_show);
        btBackDVNL.setEnabled(is_show);
        btHoanTatDVNL.setEnabled(is_show);
        
        if (is_show) {
            lichEnable(!is_show);
            nhanvienPVEnable(!is_show);
        }
    }
    
    
    private void nhanvienPVEnable(boolean is_show) {
        tbShowNVPV.setEnabled(is_show);
        btChonLaiNVPV.setEnabled(is_show);
        if (is_show) {
            lichEnable(!is_show);
            dichvuNLEnable(!is_show);
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBackDVNL;
    private javax.swing.JButton btChonLaiNVPV;
    private javax.swing.JButton btHoanTatDVNL;
    private javax.swing.JButton btHoanTatNhanKhach;
    private javax.swing.JButton btnSearchDVNL;
    private javax.swing.JButton btnSearchKhach;
    private javax.swing.JButton btnTaoLich;
    private javax.swing.JComboBox<String> cbDVNL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbLich;
    private javax.swing.JLabel lbSdtKH;
    private javax.swing.JLabel lbTenKH;
    private javax.swing.JLabel lbTongtienTamTinh;
    private javax.swing.JPanel panel_search_dv_nl;
    private javax.swing.JPanel panel_search_lich;
    private javax.swing.JPanel pannel_add_dv_nl;
    private javax.swing.JTable tbShowBillTamTinh;
    private javax.swing.JTable tbShowDVNL;
    private javax.swing.JTable tbShowLich;
    private javax.swing.JTable tbShowNVPV;
    private javax.swing.JScrollPane tbl_choose_nv;
    private javax.swing.JTextField tfSearchNLDV;
    private javax.swing.JTextField tfSearchNameKH;
    // End of variables declaration//GEN-END:variables
}
