
import db.KhachHangDB;
import java.util.List;
import javax.swing.JOptionPane;
import model.KhachHang;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author beetsoft
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    static boolean is_show = false;
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel_search_lich = new javax.swing.JPanel();
        tfSearchNameKH = new javax.swing.JTextField();
        btnSearchKhach = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbShowLich = new javax.swing.JTable();
        btnTaoLich = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pannel_add_dv_nl = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tbl_choose_nv = new javax.swing.JScrollPane();
        tbShowNVPV = new javax.swing.JTable();
        btHoanTatNVPV = new javax.swing.JButton();
        btBackNVPV = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        panel_search_dv_nl = new javax.swing.JPanel();
        tfSearchNLDV = new javax.swing.JTextField();
        btnSearchDVNL = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbShowDVNL = new javax.swing.JTable();
        btHoanTatDVNL = new javax.swing.JButton();
        btBackDVNL = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbShowBillTamTinh = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lbTongtienTamTinh = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btHoanTatNhanKhach = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel1.setText("Chuc nang nhan khach");

        panel_search_lich.setBackground(new java.awt.Color(242, 242, 240));
        panel_search_lich.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tim lich dat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        tfSearchNameKH.setToolTipText("Nhap ten");
        tfSearchNameKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchNameKHActionPerformed(evt);
            }
        });

        btnSearchKhach.setText("Tim");
        btnSearchKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchKhachActionPerformed(evt);
            }
        });

        tbShowLich.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Tran The Lam", "02323230203am", "lamtt@gmail.com", "09:30 2019-11-01"},
                {"Nguyen Văn Lam", "9423498a", "banv@gmail.com", "20:30 2019-11-01"}
            },
            new String [] {
                "Ten ", "So dien thoai", "Email", "Lich"
            }
        ));
        jScrollPane1.setViewportView(tbShowLich);

        btnTaoLich.setText("Tao Lich");
        btnTaoLich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoLichActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_search_lichLayout = new javax.swing.GroupLayout(panel_search_lich);
        panel_search_lich.setLayout(panel_search_lichLayout);
        panel_search_lichLayout.setHorizontalGroup(
            panel_search_lichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_search_lichLayout.createSequentialGroup()
                .addGroup(panel_search_lichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_search_lichLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panel_search_lichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(panel_search_lichLayout.createSequentialGroup()
                                .addComponent(tfSearchNameKH, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(btnSearchKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_search_lichLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTaoLich, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_search_lichLayout.setVerticalGroup(
            panel_search_lichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_search_lichLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_search_lichLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearchNameKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchKhach))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTaoLich)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pannel_add_dv_nlLayout = new javax.swing.GroupLayout(pannel_add_dv_nl);
        pannel_add_dv_nl.setLayout(pannel_add_dv_nlLayout);
        pannel_add_dv_nlLayout.setHorizontalGroup(
            pannel_add_dv_nlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1293, Short.MAX_VALUE)
        );
        pannel_add_dv_nlLayout.setVerticalGroup(
            pannel_add_dv_nlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 744, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chon nhan vien phuc vu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        tbShowNVPV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Cat toc", "1", "Tran Van A"},
                {"3", "Goi Dau", "2", "Nguyen Van B"}
            },
            new String [] {
                "MaDV", "TenDV", "MaNV", "TenNV"
            }
        ));
        tbl_choose_nv.setViewportView(tbShowNVPV);

        btHoanTatNVPV.setText("Hoan tat");
        btHoanTatNVPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoanTatNVPVActionPerformed(evt);
            }
        });

        btBackNVPV.setText("Quay Lai");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbl_choose_nv, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btBackNVPV)
                        .addGap(32, 32, 32)
                        .addComponent(btHoanTatNVPV, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl_choose_nv, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHoanTatNVPV)
                    .addComponent(btBackNVPV))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        panel_search_dv_nl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Them dich vu, nguyen lieu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        tfSearchNLDV.setText("Nhap ten dich vu/nguyen lieu");
        tfSearchNLDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchNLDVActionPerformed(evt);
            }
        });

        btnSearchDVNL.setText("Tim kiem");
        btnSearchDVNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDVNLActionPerformed(evt);
            }
        });

        tbShowDVNL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Cat toc nam", "50", "cat toc nam"},
                {"2", "Cat toc nu", "60", "cat toc nua"}
            },
            new String [] {
                "Ma", "Ten DV/NL", "Don gia(nghin vnd)", "Mo ta"
            }
        ));
        jScrollPane3.setViewportView(tbShowDVNL);

        btHoanTatDVNL.setText("Hoan Tat");

        btBackDVNL.setText("Quay Lai");

        javax.swing.GroupLayout panel_search_dv_nlLayout = new javax.swing.GroupLayout(panel_search_dv_nl);
        panel_search_dv_nl.setLayout(panel_search_dv_nlLayout);
        panel_search_dv_nlLayout.setHorizontalGroup(
            panel_search_dv_nlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_search_dv_nlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_search_dv_nlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(panel_search_dv_nlLayout.createSequentialGroup()
                        .addComponent(tfSearchNLDV, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(btnSearchDVNL)
                        .addGap(51, 51, 51)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_search_dv_nlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBackDVNL)
                .addGap(62, 62, 62)
                .addComponent(btHoanTatDVNL)
                .addGap(54, 54, 54))
        );
        panel_search_dv_nlLayout.setVerticalGroup(
            panel_search_dv_nlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_search_dv_nlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_search_dv_nlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchDVNL)
                    .addComponent(tfSearchNLDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panel_search_dv_nlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btHoanTatDVNL)
                    .addComponent(btBackDVNL))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hoa don tam tinh", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        tbShowBillTamTinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Cat toc nam", "50", "1"},
                {"3", "Goi dau", "30", "1"}
            },
            new String [] {
                "Ma", "Ten DV/NL", "Don gia(nghin vnd)", "So luong"
            }
        ));
        jScrollPane4.setViewportView(tbShowBillTamTinh);

        jLabel2.setText("Tong tien :");

        lbTongtienTamTinh.setText("80");

        jLabel4.setText("(nghin vnd)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addComponent(lbTongtienTamTinh)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbTongtienTamTinh)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_search_dv_nl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(362, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(panel_search_dv_nl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        btHoanTatNhanKhach.setText("Hoan tat");
        btHoanTatNhanKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoanTatNhanKhachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_search_lich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(513, 513, 513)
                        .addComponent(btHoanTatNhanKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pannel_add_dv_nl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(474, 474, 474)
                .addComponent(jLabel1)
                .addContainerGap(2386, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panel_search_lich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(pannel_add_dv_nl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btHoanTatNhanKhach)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHoanTatNhanKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoanTatNhanKhachActionPerformed
        // TODO add your handling code here:
        if (is_show){
            jLabel1.setEnabled(true);
            is_show = false;
            return;
        } 
        jLabel1.setEnabled(false);
        is_show = true;
    }//GEN-LAST:event_btHoanTatNhanKhachActionPerformed

    private void tfSearchNameKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchNameKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchNameKHActionPerformed

    private void btnSearchKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchKhachActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(this, "Hay dat lich cho khach khang",
//                "Khach hang chua dat lich", JOptionPane.YES_NO_OPTION);
        String ten = tfSearchNameKH.getText();
        KhachHangDB kdb = new KhachHangDB();
        List<KhachHang> lkh = kdb.get_by_name(ten);
        
                

    }//GEN-LAST:event_btnSearchKhachActionPerformed

    private void tfSearchNLDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchNLDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchNLDVActionPerformed

    private void btnSearchDVNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDVNLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchDVNLActionPerformed

    private void btnTaoLichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoLichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaoLichActionPerformed

    private void btHoanTatNVPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoanTatNVPVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btHoanTatNVPVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBackDVNL;
    private javax.swing.JButton btBackNVPV;
    private javax.swing.JButton btHoanTatDVNL;
    private javax.swing.JButton btHoanTatNVPV;
    private javax.swing.JButton btHoanTatNhanKhach;
    private javax.swing.JButton btnSearchDVNL;
    private javax.swing.JButton btnSearchKhach;
    private javax.swing.JButton btnTaoLich;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbTongtienTamTinh;
    private javax.swing.JPanel panel_search_dv_nl;
    private javax.swing.JPanel panel_search_lich;
    private javax.swing.JPanel pannel_add_dv_nl;
    private javax.swing.JTable tbShowBillTamTinh;
    private javax.swing.JTable tbShowDVNL;
    private javax.swing.JTable tbShowLich;
    private javax.swing.JTable tbShowNVPV;
    private javax.swing.JScrollPane tbl_choose_nv;
    private javax.swing.JTextField tfSearchNLDV;
    private javax.swing.JTextField tfSearchNameKH;
    // End of variables declaration//GEN-END:variables
}
